sudo: false
language: c
cache:
  directories:
  - $HOME/.stack
  - $HOME/android

before_install:
# Download and unpack the stack executable
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'
- export PATH=/opt/ghc/$GHCVER/bin:$PATH
- bash ./scripts/fetch-android-sdk.sh
- export PATH=$PATH:$HOME/android/android-sdk-linux/build-tools/23.0.1

matrix:
  include:
  - env: GHCVER=7.8.4 STACK_YAML=stack-7.8.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.8.4
        - ia32-libs-multilib
        - ia32-libs
        - libgd2-xpm
        - openjdk-7-jdk
  - env: GHCVER=7.10.3 STACK_YAML=stack-7.10.yaml
    addons:
      apt:
        sources:
        - hvr-ghc
        packages:
        - ghc-7.10.3
        - ia32-libs-multilib
        - ia32-libs
        - libgd2-xpm
        - openjdk-7-jdk

script:
 - stack --no-terminal --skip-ghc-check build
 - stack --no-terminal --skip-ghc-check test
